version: "3.5"

services:
  webapi:
    build:
      context: ./FingergunsApi/FingergunsApi.App
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"

  client:
    build:
      context: ./fingerguns-client
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./fingerguns-client/nginx/logs/:/var/log/nginx/
