version: "3.5"

services:
  mariadb:
    image: mariadb:10.5
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=fingerguns

  webapi:
    build:
      context: ./FingergunsApi/FingergunsApi.App
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - mariadb

  client:
    build:
      context: ./fingerguns-client
      dockerfile: Dockerfile
    volumes:
      - ./fingerguns-client/nginx/logs/:/var/log/nginx/
