version: "3.5"

services:
  webapi:
    build:
      dockerfile: Dockerfile.dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
    ports:
      - "5001:5001"
    volumes:
      - ./FingergunsApi/.aspnet/https:/https:ro

  client:
    build:
      context: ./fingerguns-client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./common/tls/:/etc/letsencrypt/live/fingerguns.co
      - ./fingerguns-client/src/:/app/src
